name: Run a notebook in databricks on PRs

on:
 push:
 pull_request:

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         local-notebook-path: RUNME.py
         databricks-host: https://e2-demo-field-eng.cloud.databricks.com
         databricks-token: ${{ secrets.DEPLOYMENT_TARGET_TOKEN_AWS }}
         new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "Standard_D3_v2"
           }
         notebook-params-json: >
           {
            "run_job": "True"
           }
           
